{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "skooner.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "skooner.fullname" . }}
  labels:
{{- include "skooner.labels" . | nindent 4 }}
  {{- with .Values.podDisruptionBudget.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "skooner.selectorLabels" . | nindent 6 }}
{{- end }}

