image:
  repository: tccr.io/truecharts/syslog-ng
  pullPolicy: IfNotPresent
  tag: 4.0.1@sha256:e3157f1638eb2c107fec3d6fa28bcece53571db19f314c6eb57c9182a8bc0658

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env: {}

service:
  main:
    ports:
      main:
        targetPort: 601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: UDP
        targetPort: 514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: false
