image:
  repository: tccr.io/truecharts/syslog-ng
  pullPolicy: IfNotPresent
  tag: 10.0.6@sha256:16b4c38395c13237220ae0751d5c7597447896590f1da8d0fa6d91d7b4b15529

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env: {}

service:
  main:
    ports:
      main:
        targetPort: 601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: UDP
        targetPort: 514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: false
