apiVersion: v2
appVersion: 10.7.5
description: Jellyfin
home: https://github.com/kfirfer/helm/tree/master/charts/jellyfin
icon: https://developer.asustor.com/uploadIcons/0020_999_1568614440_Jellyfin_256.png
maintainers:
- email: kfirfer@gmail.com
  name: kfir
name: jellyfin
version: 2.0.2
