{{- if .Values.rbac.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kibana-index-pattern-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kibana-index-pattern-updater.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - 'list'
  - 'get'
{{- end }}
