{{- if .Values.rbac.createClusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "pod-cleanup.fullname" . }}
roleRef:
  name: {{ .Release.Namespace }}-{{ include "pod-cleanup.fullname" . }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: {{ include "pod-cleanup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
{{- end }}