{{- if .Values.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pod-cleanup.fullname" . }}-certs
stringData:
{{- range $path, $config := .Values.certificates }}
  {{ $path }}: |
{{- if eq (typeOf $config) "string" }}
{{- $config | nindent 4 }}
{{- else }}
{{- toYaml $config | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
