apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pod-cleanup.fullname" . }}-secret-env
  labels:
{{- include "pod-cleanup.labels" . | nindent 4 }}
stringData:
{{ toYaml .Values.secret | indent 2 }}
