{{- if .Values.rbac.createClusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scripts.fullname" . }}
roleRef:
  name: {{ include "scripts.fullname" . }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: {{ include "scripts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
{{- end }}