{{- if .Values.secretFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scripts.fullname" . }}
  labels:
{{- include "scripts.labels" . | nindent 4 }}
stringData:
{{- range $path, $config := .Values.secretFiles }}
  {{ $path }}: |
{{- if eq (typeOf $config) "string" }}
{{- $config | nindent 4 -}}
{{- else }}
{{- toYaml $config | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}

