{{- if .Values.podSecurityPolicy.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "mysqldump.fullname" . }}-{{ .Release.Namespace }}-clusterrole
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "mysqldump.fullname" . }}-{{ .Release.Namespace }}-psp
    verbs:
      - use
{{- end }}
