apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}-headless
  labels:
    {{- include "garage.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: cluster
      port: 3901
      targetPort: cluster
      protocol: TCP
      {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
      appProtocol: tcp
      {{- end }}
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
