# Created auth by using this command: "htpasswd -c auth admin",  than "base64 auth"
apiVersion: v1
data:
  auth: YWRtaW46JGFwcjEkeFhoUWFsOXMkakY5T1RLRUpaRWNTSTdwSFJ2RGc4Lwo=
kind: Secret
metadata:
  name: secret-auth
type: Opaque