apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quickwit.fullname" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
data:
  node.yaml: |-
    version: 0.6
    listen_address: 0.0.0.0
    gossip_listen_port: 7282
    data_dir: /quickwit/qwdata
    default_index_root_uri: {{ .Values.config.default_index_root_uri }}
    {{- with .Values.config.indexer }}
    indexer:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.config.storage }}
    {{- $new_storage := . | deepCopy }}
    {{- /* s3 access_key_id and secret_access_key are already set by env variables */}}
    {{ if .s3 }}
    {{- $_ := unset $new_storage.s3 "access_key_id" }}
    {{- $_ := unset $new_storage.s3 "secret_access_key" }}
    {{- end }}
    {{- /* azure account and access_key are already set by env variables */}}
    {{ if .azure }}
    {{- $_ := unset $new_storage.azure "account" }}
    {{- $_ := unset $new_storage.azure "access_key" }}
    {{- end }}
    storage:
      {{- toYaml $new_storage | nindent 6 }}
    {{- end }}
    {{- with .Values.config.ingest_api }}
    ingest_api:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.config.searcher }}
    searcher:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.config.jaeger }}
    jaeger:
      {{- toYaml . | nindent 6 }}
    {{- end }}
