apiVersion: v1
kind: Service
metadata:
  name: {{ include "pmm-server.fullname" . }}
  labels:
    {{- include "pmm-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pmm-server.selectorLabels" . | nindent 4 }}
