apiVersion: v2
description: A Helm chart to periodically check the status of your services with heartbeat
icon: https://www.elastic.co/jp/assets/blt75e7956191e1bd55/icon-heartbeat-bb.svg
name: heartbeat
version: 8.6.2
appVersion: 8.6.2
home: https://www.elastic.co/products/beats/heartbeat
sources:
- https://www.elastic.co/guide/en/beats/heartbeat/current/index.html

