apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "mysql-check.fullname" . }}
  labels:
    app: {{ template "mysql-check.name" . }}
    chart: {{ template "mysql-check.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.cronjob.labels }}
{{ toYaml .Values.cronjob.labels | indent 4 }}
{{- end }}
{{- if .Values.cronjob.annotations }}
  annotations:
{{ toYaml .Values.cronjob.annotations | indent 4 }}
{{- end }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  {{- with .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app: {{ template "mysql-check.name" . }}
        release: {{ .Release.Name }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            app: {{ template "mysql-check.name" . }}
            release: {{ .Release.Name }}
{{- if .Values.pod.labels }}
{{ toYaml .Values.pod.labels | indent 12 }}
{{- end }}
{{- if .Values.pod.annotations }}
          annotations:
{{ toYaml .Values.pod.annotations | indent 12 }}
{{- end }}
        spec:
{{- if .Values.extraVolumes }}
          volumes:
{{ toYaml .Values.extraVolumes | indent 12 }}
{{- end }}
          restartPolicy: {{ .Values.cronjob.jobRestartPolicy }}
{{- if .Values.priorityClassName }}
          priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
{{- if .Values.image.pullSecret }}
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret }}
{{- end }}
{{- if .Values.extraInitContainers }}
          initContainers:
{{- range $key, $value := .Values.extraInitContainers }}
          - name: "{{ $key }}"
{{ toYaml $value | indent 12 }}
{{- end }}
{{- end }}
        {{- if .Values.rbac.enabled }}
          serviceAccountName: {{ template "mysql-check.serviceAccountName" .}}
          automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
        {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.extraVolumeMounts }}
              volumeMounts:
{{ toYaml .Values.extraVolumeMounts | indent 16 }}
{{ end }}
{{ if .Values.command }}
              command:
{{ toYaml .Values.command | indent 16 }}
{{- end }}
              envFrom:
                - secretRef:
                    name: {{ template "mysql-check.fullname" . }}-secret-env
              env:
{{- if .Values.envFromSecrets }}
{{- range $key,$value := .Values.envFromSecrets }}
              - name: {{ $key | upper | quote}}
                valueFrom:
                  secretKeyRef:
                    name: {{ $value.from.secret | quote}}
                    key: {{ $value.from.key | quote}}
{{- end }}
{{- end }}
{{- if .Values.env }}
{{- range $key,$value := .Values.env }}
              - name: {{ $key | upper | quote}}
                value: {{ $value | quote}}
{{- end }}
{{- end }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
    {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
    {{- end }}
