apiVersion: v1
kind: Secret
metadata:
  name: {{ template "percona-xtradb-cluster.fullname" . }}
  labels:
    app: {{ template "percona-xtradb-cluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlPassword }}
  mysql-password:  {{ .Values.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.xtraBackupPassword }}
  xtrabackup-password:  {{ .Values.xtraBackupPassword | b64enc | quote }}
  {{ else }}
  xtrabackup-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.pmm.enabled }}
  pmm-server-password: {{ .Values.pmm.password | b64enc | quote }}
  {{ end }}
{{- if .Values.ssl.enabled }}
{{ if .Values.ssl.certificates }}
{{- range .Values.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "percona-xtradb-cluster.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.pem: {{ .ca | b64enc }}
  ca-key.pem: {{ .cakey | b64enc }}
  client-cert.pem: {{ .clientcert | b64enc }}
  client-key.pem: {{ .clientkey | b64enc }}
  private_key.pem: {{ .privatekey | b64enc }}
  public_key.pem: {{ .publickey | b64enc }}
  server-cert.pem: {{ .servercert | b64enc }}
  server-key.pem: {{ .serverkey | b64enc }}
{{- end }}
{{- end }}
{{- end }}
